# This file is auto-generated by : C:\JTSDK64-Tools\jtsdk64.ps1 version v3.2.1.0a3
# Tool Chain File for Qt 5.15.2
 
# System Type and Based Paths
SET (CMAKE_SYSTEM_NAME Windows)
SET (QTDIR C:/JTSDK64-Tools/tools/Qt/5.15.2/mingw81_64/bin)
SET (GCCD C:/JTSDK64-Tools/tools/Qt/Tools/mingw810_64/bin)
 
# AsciiDoctor
SET (ADOCD C:/JTSDK64-Tools/tools/ruby/3.0.2-1)
 
# FFTW
SET (FFTWD C:/JTSDK64-Tools/tools/fftw/3.3.9)
SET (FFTW3_LIBRARY C:/JTSDK64-Tools/tools/fftw/3.3.9/libfftw3-3.dll)
SET (FFTW3F_LIBRARY C:/JTSDK64-Tools/tools/fftw/3.3.9/libfftw3f-3.dll)
 
# Hamlib
SET (HLIB C:/JTSDK64-Tools/tools/hamlib/qt/5.15.2)
 
# Subversion
SET (SVND C:/JTSDK64-Tools/tools/subversion/1.14.1)
 
# PortAudio
SET (PALIB C:/JTSDK64-Tools/tools/portaudio)
SET (PALIB_LIBRARY C:/JTSDK64-Tools/tools/portaudio/lib/libportaudio.dll)
 
# Cmake Consolidated Variables
SET (CMAKE_PREFIX_PATH ${GCCD} ${QTDIR} ${HLIB} ${HLIB}/bin ${ADOCD} ${FFTWD} ${FFTW3_LIBRARY} ${FFTW3F_LIBRARY} ${SVND} ${PALIB} ${PALIB_LIBRARY})
SET (CMAKE_FIND_ROOT_PATH ${JTSDK_TOOLS})
SET (CMAKE_FIND_ROOT_PATH_PROGRAM NEVER)
SET (CMAKE_FIND_ROOT_PATH_LIBRARY BOTH)
SET (CMAKE_FIND_ROOT_PATH_INCLUDE BOTH)
 
# END Cmake Tool Chain File
